/**
 * Zero-dependency token build. Reads tokens.json and emits:
 *   dist/tokens.ts                 typed object + light/dark themes (web / admin)
 *   dist/tokens.css                :root custom properties + dark override
 *   ../../mobile/lib/design/tokens.g.dart   Flutter ThemeExtension source
 *
 * Run: pnpm --filter @grandprice/tokens build
 * (Style Dictionary can replace this later if the token graph grows.)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const T = JSON.parse(readFileSync(resolve(here, "tokens.json"), "utf8"));

const distDir = resolve(here, "dist");
const mobileDir = resolve(here, "../../mobile/lib/design");
mkdirSync(distDir, { recursive: true });
mkdirSync(mobileDir, { recursive: true });

const resolveRefs = (obj) => {
  const flat = {};
  const walk = (o, path = []) => {
    for (const [k, v] of Object.entries(o)) {
      if (k.startsWith("$")) continue;
      if (v && typeof v === "object" && !Array.isArray(v)) walk(v, [...path, k]);
      else flat[[...path, k].join(".")] = v;
    }
  };
  walk(obj);
  const deref = (val) =>
    typeof val === "string" && val.startsWith("{") && val.endsWith("}")
      ? deref(flat[val.slice(1, -1)])
      : val;
  for (const key of Object.keys(flat)) flat[key] = deref(flat[key]);
  return flat;
};

const flat = resolveRefs(T);

// ---- tokens.ts ------------------------------------------------------------
writeFileSync(
  resolve(distDir, "tokens.ts"),
  `// GENERATED by packages/tokens/build.mjs — do not edit.\n` +
    `export const tokens = ${JSON.stringify(T, null, 2)} as const;\n` +
    `export const light = ${JSON.stringify(resolveThemed(T.semantic.light), null, 2)} as const;\n` +
    `export const dark = ${JSON.stringify(resolveThemed(T.semantic.dark), null, 2)} as const;\n` +
    `export type Tokens = typeof tokens;\n`,
);

function resolveThemed(theme) {
  const out = {};
  for (const [k, v] of Object.entries(theme)) {
    out[k] =
      typeof v === "string" && v.startsWith("{")
        ? flat[v.slice(1, -1)]
        : v;
  }
  return out;
}

// ---- tokens.css ---------------------------------------------------------
const cssVars = (theme) =>
  Object.entries(resolveThemed(theme))
    .map(([k, v]) => `  --gp-${kebab(k)}: ${v};`)
    .join("\n");
const scale = (prefix, obj) =>
  Object.entries(obj)
    .map(([k, v]) => `  --gp-${prefix}-${k}: ${typeof v === "number" ? v + "px" : v};`)
    .join("\n");

writeFileSync(
  resolve(distDir, "tokens.css"),
  `/* GENERATED by packages/tokens/build.mjs — do not edit. */\n` +
    `:root {\n${cssVars(T.semantic.light)}\n${scale("space", T.space)}\n${scale("radius", T.radius)}\n}\n\n` +
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${cssVars(T.semantic.dark)}\n  }\n}\n\n` +
    `:root[data-theme="dark"] {\n${cssVars(T.semantic.dark)}\n}\n`,
);

// ---- tokens.g.dart ----------------------------------------------------
const dartColor = (hexOrRgba) => {
  const m = /^#([0-9a-f]{6})$/i.exec(hexOrRgba);
  if (m) return `Color(0xFF${m[1].toUpperCase()})`;
  const r = /rgba?\(([^)]+)\)/.exec(hexOrRgba);
  if (r) {
    const [rr, gg, bb, aa = "1"] = r[1].split(",").map((s) => s.trim());
    const h = (n) => Number(n).toString(16).toUpperCase().padStart(2, "0");
    const a = h(Math.round(parseFloat(aa) * 255));
    return `Color(0x${a}${h(rr)}${h(gg)}${h(bb)})`;
  }
  return `Color(0xFF000000) /* ${hexOrRgba} */`;
};

const themeFields = (theme) =>
  Object.entries(resolveThemed(theme))
    .map(([k, v]) => `    ${k}: ${dartColor(v)},`)
    .join("\n");

const typeRoles = Object.entries(T.type.roles)
  .map(
    ([k, r]) =>
      `  static const ${k} = GpTextRole(family: '${T.type.families[r.family]}', weight: ${r.weight}, size: ${r.size}, height: ${r.height});`,
  )
  .join("\n");

const dart = `// GENERATED by packages/tokens/build.mjs — do not edit.
import 'package:flutter/material.dart';

class GpTextRole {
  final String family;
  final int weight;
  final double size;
  final double height;
  const GpTextRole({required this.family, required this.weight, required this.size, required this.height});
  FontWeight get fontWeight => FontWeight.values[(weight ~/ 100) - 1];
}

class GpType {
${typeRoles}
}

class GpSpace {
${Object.entries(T.space).map(([k, v]) => `  static const s${k} = ${v}.0;`).join("\n")}
}

class GpRadius {
${Object.entries(T.radius).map(([k, v]) => `  static const ${k.replace(/^(\d)/, "r\$1")} = ${v}.0;`).join("\n")}
}

@immutable
class GpColors extends ThemeExtension<GpColors> {
  final Color bg, surface, surfaceSunken, border, borderStrong, overlay;
  final Color textHi, textMed, textLow;
  final Color primary, onPrimary, primaryContainer, onPrimaryContainer;
  final Color success, successContainer, rating, error, errorContainer, skeleton;
  const GpColors({
    required this.bg, required this.surface, required this.surfaceSunken,
    required this.border, required this.borderStrong, required this.overlay,
    required this.textHi, required this.textMed, required this.textLow,
    required this.primary, required this.onPrimary, required this.primaryContainer, required this.onPrimaryContainer,
    required this.success, required this.successContainer, required this.rating,
    required this.error, required this.errorContainer, required this.skeleton,
  });

  static const light = GpColors(
${themeFields(T.semantic.light)}
  );

  static const dark = GpColors(
${themeFields(T.semantic.dark)}
  );

  @override
  GpColors copyWith() => this;
  @override
  GpColors lerp(ThemeExtension<GpColors>? other, double t) => this;
}
`;
writeFileSync(resolve(mobileDir, "tokens.g.dart"), dart);

function kebab(s) {
  return s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
}

console.log("tokens: wrote dist/tokens.ts, dist/tokens.css, mobile/lib/design/tokens.g.dart");
